language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8.11'
before_script:
  - yarn global add codecov
  - yarn install
script:
  - yarn run build && yarn run test:prod
after_success:
  - codecov
