language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- '8.11'
before_script:
- yarn global add codecov
- yarn install
script:
- yarn run build && yarn run test:prod
deploy:
  provider: npm
  on:
    tags: true
  skip_cleanup: true
  email: lostintime.dev@gmail.com
  api_key:
    secure: P6XvKQEBrGJDapFcuQV9C+hVNILiZ2/mtzNKQFf0SdLIY3QfmA1pGVxS5gim7MqZt/0y+AY5zpZOV1Gay4+5KQEyrscAoDWEr3SQ38CmXbFRS/HKi+9Hj2wezxfjjHjLX1wVhS1wrqJOb+kbzUEHWpsghyCM8n4WPZbcmuYxA1+xNEtSTPmZm0nnCW5H58uGwsZjanQ1Qj22V5PVF25PgXntFiNLt1seDiWnLr/Soe2xAxFvYAyrdia/OozQnyenPlFp3IQ8GR6HHWtgX4S8ieYMStHZb+HBUKmK1K6BeCHiH+tguLDM+HLFZgzbb3g7aGACLpBlD4NZ+ICRe6u8BpbmfUbKwWtsBvu3hv9NGqGRf/J2gXQa2+mJR8/72tRsd7ILPIibQSAv5Oqosr9SDuLK/2AOfshoZlBrghHHIQjV+mgYtgcIKN5SSOKVVH2gkARfpArNXnWP453JzfHVi3Bnlg451UVjFqvLIn8Pgp/r0p/r+0xox+jnaifum2Wqna6v7taOzz9l8zHyTb1ETzZEGD15RvkVwbRLlLXyf8kXeZsGrzWGgDXZq46aME338QyzagMY3nfuQJ1DjXZytiQtGk3UVw7oG31WcTxCYUw9hPjeYg0K2669tKEgwk2Svd1mDDZs3HGcYxrPJOzlPh33bBb8aw9fFfePhQH48KU=
after_success:
- codecov
